apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: is-comment-b
spec:
  params:
  - name: comment
    type: string
  check:
    image: alpine
    script: |
      #!/bin/sh
      if [ $(params.comment) == "/b" ]; then
        exit 0
      else
        exit 1
      fi