apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: is-comment-a
spec:
  params:
  - name: comment 
    type: string
  check:
    image: ubuntu
    script: |
      #!/bin/bash

      #Define the string to split
      # comment="/lgtm\r\n/approve"
      comment="$(params.comment)"
      # a="/lgtm\r\n/approve\r\n/test"
      # b=$(echo -e $a)
      # for i in $b
      # do
      #   echo $i
      #   if [ $i == "/lgtm" ]; then
      #     echo "test-if"
      #   fi
      # done

      # echo $comment
      # b=$(printf $comment)

      #Define multi-character delimiter
      delimiter='\r\n'

      #Concatenate the delimiter with the main string
      string=$comment$delimiter

      #Split the text based on the delimiter
      comment_array=()
      while [[ $string ]]; do
      comment_array+=( "${string%%"$delimiter"*}" )
      string=${string#*"$delimiter"}
      done

      #Print the words after the split
      is_run=false

      for value in ${comment_array[@]}
      do
      echo "$value"
      if [ $value == "/lgtm" ]
      then
          is_run=true
          echo "test-loop"
          break
      fi

      done

      echo "$is_run"


      if [ "$is_run" = true ]; then
        exit 0
      # echo "true"
      else
        exit 1
      # echo "false"
      fi
