apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-eventlistener
  description: |
    This Task will add a webhook to a github repository.
spec:
  params:
    - name: filename
      description: kubeconfig file name
      type: string
  workspaces:
    - name: input
      readOnly: true
    - name: yaml-workspace
  results:
    - name: payload_url
      description: |
        The URL to which the payloads will be delivered.
        Will be used in the webhook creator task.

  steps:
    - name: add-webhook
      image: quay.io/openshift/origin-cli:latest
      script: | 

        export KUBECONFIG="$(workspaces.input.path)/$(inputs.params.filename)"

        kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
        
        oc apply --filename https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml

        oc apply -f https://raw.githubusercontent.com/tektoncd/catalog/v1beta1/git/git-clone.yaml


        oc apply -f '$(workspaces.yaml-workspace.path)/.'
        
        oc expose svc el-github-listener-interceptor
        PAYLOAD_URL="$(oc  get route el-github-listener-interceptor --template='http://{{.spec.host}}')"

        echo -n "$PAYLOAD_URL" > $(results.payload_url.path)